<a href="https://colab.research.google.com/github/io-uty/skt-bigdata-analysis/blob/main/02_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas
  - Data 분석
  - DataFrame (Series) <- List, Dict, Array
  - Coding하는 Excel
  - 데이터 조작 및 분석을 위한 파이썬 프로그래밍 라이브러리
  - numpy를 기반으로 하여 처리 속도가 빠름
  - 데이터 조작을 위한 빠르고 효율적인 데이터 프레임 객체
  - 데이터 구조 정렬을 포함한 통합된 결손치 처리
  - 열 데이터의 정렬과 다양한 데이터 조작

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

### Pandas
- pandas의 기본 구조
- 데이터 프레임의 정보 확인
- 결측치 확인 및 처리 - 인덱싱과 슬라이싱
- 데이터 프레임의 변경
- 통계 데이트 계산
- 그룹핑 함수
---
- Series객체
  - 1차원 배열 구조를 가지며 인덱스를 가진다
  - dtype 속성과 shape 속성 등을 가진다

In [ ]:
a1 = [3,5,-1,4]
s1 = pd.Series(a1)
print(s1)
print(type(s1),s1.dtype)
print(s1.index)
#Series 안 : 동일, 밖: 다른타입 가능

0    3
1    5
2   -1
3    4
dtype: int64
<class 'pandas.core.series.Series'> int64
RangeIndex(start=0, stop=4, step=1)

In [ ]:
b1 = ['A', 'B', 'C', 'D']
b2 = ['가', '나', '다','라']

s2 = pd.Series(b1,index=b2)
print(s2type(s2), s2.dtype)
print(s2)

print(s1[2], s2[2],s2['다'])

가    A
나    B
다    C
라    D
dtype: object <class 'pandas.core.series.Series'> object
가    A
나    B
다    C
라    D
dtype: object
-1 C C

/tmp/ipykernel_18793/3849372044.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s1[2], s2[2],s2['다'])

In [ ]:
c1 = {'Jane': 80, 'Tom':70, 'Alice':90, 'Hong':100}
s3 = pd.Series(c1)
print(s3)

print(s3.index)
print(s3.values)

Jane      80
Tom       70
Alice     90
Hong     100
dtype: int64
Index(['Jane', 'Tom', 'Alice', 'Hong'], dtype='object')
[ 80  70  90 100]

In [ ]:
c2 = {'name' : ['Jane', 'Tom' , 'Alice', 'Hong'],
      'age' : [34,27,51,45],
      'point' : [80,70,90,100]}

s4 = pd.Series(c2)
print(s4)

name     [Jane, Tom, Alice, Hong]
age              [34, 27, 51, 45]
point           [80, 70, 90, 100]
dtype: object

In [ ]:
z1 = [1,2,3,None,5]
#print(sum(z1))

s5 = pd.Series(z1)
print(s5)
print(sum(s5))

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64
nan

In [ ]:
import numpy as np

s6 = pd.Series([1,2,3,np.nan,5]) #주소 빈 게 아니라, 수치연산 불가
print(s6)

s7 = pd.Series([1,2,3,4,5])
print(s7)

print(sum(s7))
print(sum(s5))
print(sum(s6))

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int64
15
nan
nan

In [ ]:
d1 = pd.DataFrame(c2)
print(d1) #Series를 DataFrame으로

    name  age  point
0   Jane   34     80
1    Tom   27     70
2  Alice   51     90
3   Hong   45    100

- DataFrame 객체
  - 2차원 배열 구조를 가지며 index를 가진다.
  - 행(row)과 열(col)로 구성되고 각 열은 이름을 가진다.
  - 각 열은 각각의 data type을 가진다.

In [ ]:
x = [['Jackson', 68, True, 1.5, 'A'],
     ['Liam', 74, True, 1.1, 'A'],
     ['Emma', 20, False, 0.89, 'C']]
df = pd.DataFrame(x, columns = ['Name', 'Weight','Option',"Etc", "Type"])

print("type: ",type(df))
print("shape: ", df.shape)
print(df)

type:  <class 'pandas.core.frame.DataFrame'>
shape:  (3, 5)
      Name  Weight  Option   Etc Type
0  Jackson      68    True  1.50    A
1     Liam      74    True  1.10    A
2     Emma      20   False  0.89    C

- Dictionary로 DataFrame 생성

In [ ]:
data = {
    'Name' : ['Jackson', 'Emma','Noah','James'],
    'Weight' : [68,74,77,78],
    'Option' : [True,True,False,False],
    'Rate':[0.21,1.1,0.89,0.91],
    'Type' : ['A','A','C','C']
}

df = pd.DataFrame(data)
print("type: ",type(df))
print("shape: ", df.shape)
print(df)

type:  <class 'pandas.core.frame.DataFrame'>
shape:  (4, 5)
      Name  Weight  Option  Rate Type
0  Jackson      68    True  0.21    A
1     Emma      74    True  1.10    A
2     Noah      77   False  0.89    C
3    James      78   False  0.91    C

In [ ]:
d1 = {'name':['Jane','Tom','Alice','Hong'],
      'age':[34,27,51,45],
      'point' : [80,70,90,100]}

#frame 개수 맞추어야 함

df1 = pd.DataFrame(d1)

print(df1)
print(type(df1))
print(df1.index) #for in range 랑 비슷하게 : 시작점, 끝점, step
print(df1.columns)
print(df1.values)

df1.index = ['학생1', '학생2', '학생3', '학생4']
print(df1)
print(df1.index)

    name  age  point
0   Jane   34     80
1    Tom   27     70
2  Alice   51     90
3   Hong   45    100
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'point'], dtype='object')
[['Jane' 34 80]
 ['Tom' 27 70]
 ['Alice' 51 90]
 ['Hong' 45 100]]
      name  age  point
학생1   Jane   34     80
학생2    Tom   27     70
학생3  Alice   51     90
학생4   Hong   45    100
Index(['학생1', '학생2', '학생3', '학생4'], dtype='object')

In [20]:
v1 = [['Jane', 34,80],
      ['Tom', 27,70],
      ['Alice', 51,90],
      ['Hong', 45,100]]


c1 = ['이름', '나이', '점수']
i1 = ['학생1', '학생2', '학생3', '학생4']

df2 = pd.DataFrame(data=v1, columns = c1, index=i1)
print(df2)

        이름  나이   점수
학생1   Jane  34   80
학생2    Tom  27   70
학생3  Alice  51   90
학생4   Hong  45  100

In [25]:
df1
df2
#둘 중 마지막 값만 출력됨

print(df1)
print(df2)

      name  age  point
학생1   Jane   34     80
학생2    Tom   27     70
학생3  Alice   51     90
학생4   Hong   45    100
        이름  나이   점수
학생1   Jane  34   80
학생2    Tom  27   70
학생3  Alice  51   90
학생4   Hong  45  100

In [31]:
#sol1 : index 호출
df2['이름']

print(df2['이름'])

학생1     Jane
학생2      Tom
학생3    Alice
학생4     Hong
Name: 이름, dtype: object

In [30]:
#sol2 : 하위 자식객체 호출 - 또 자식객체 호출 가능 / 확장가능성
df2.이름

학생1     Jane
학생2      Tom
학생3    Alice
학생4     Hong
Name: 이름, dtype: object

In [33]:
df2[['이름','점수']]
#error? 복수개의 type이 들어감 : 주소값 하나만 가능

        이름   점수
학생1   Jane   80
학생2    Tom   70
학생3  Alice   90
학생4   Hong  100

In [34]:
df2.iloc[1]
#seires형태로 바뀜

이름    Tom
나이     27
점수     70
Name: 학생2, dtype: object

In [36]:
df2[1:3]

        이름  나이  점수
학생2    Tom  27  70
학생3  Alice  51  90

In [39]:
df2[1:2] #slicing이용 시 행-열 바뀌지 않는다

      이름  나이  점수
학생2  Tom  27  70

- DB에서 WHERE 과 비슷

In [40]:
df2.loc['학생2']

이름    Tom
나이     27
점수     70
Name: 학생2, dtype: object

In [41]:
df2['학생2':'학생3']

        이름  나이  점수
학생2    Tom  27  70
학생3  Alice  51  90

In [42]:
df2[1:3]['이름']

학생2      Tom
학생3    Alice
Name: 이름, dtype: object

In [43]:
df2[1:3][['이름','나이']]

        이름  나이
학생2    Tom  27
학생3  Alice  51

In [47]:
df2.iloc[1:3][['이름','나이']]

        이름  나이
학생2    Tom  27
학생3  Alice  51

In [48]:
df2['학생2':'학생3'][['이름','나이']]

        이름  나이
학생2    Tom  27
학생3  Alice  51

In [56]:
print(df2.loc['학생1','점수']) #tip: 단일값 - print 붙이는게 좋음

80

In [50]:
df2.loc['학생1':'학생3','점수']

학생1    80
학생2    70
학생3    90
Name: 점수, dtype: int64

In [51]:
df2.loc['학생1':'학생3','나이':'점수']

     나이  점수
학생1  34  80
학생2  27  70
학생3  51  90

In [52]:
df2.loc['학생1':'학생3',:]

        이름  나이  점수
학생1   Jane  34  80
학생2    Tom  27  70
학생3  Alice  51  90

In [53]:
df2.loc[:,'나이':'점수']

     나이   점수
학생1  34   80
학생2  27   70
학생3  51   90
학생4  45  100

In [57]:
df2.loc[:,:]

        이름  나이   점수
학생1   Jane  34   80
학생2    Tom  27   70
학생3  Alice  51   90
학생4   Hong  45  100

- 90점이 넘는 학생들의 이름과 나이를 출력

In [59]:
df2[df2['점수']>=90][['이름','나이']]

        이름  나이
학생3  Alice  51
학생4   Hong  45

### 의사코드로 먼저 작성
- df2[점수 > 90점이 넘는] -> series 봐야됨 -> 2열추출
- df2[df2['점수']>90][['이름','나이']]

In [67]:
# 나이 50 넘고 점수 80보다 큰 학생의 이름, 점수 구하기
df2[(df2['나이']>50)&(df2['점수']>80)][['이름','점수']]

        이름  점수
학생3  Alice  90

In [73]:
df2.sort_values(by='점수')
df2.sort_values(by='점수',ascending=False)

        이름  나이   점수
학생4   Hong  45  100
학생3  Alice  51   90
학생1   Jane  34   80
학생2    Tom  27   70

In [77]:
#df2['나이']*df2['점수']/100
df2['보너스'] = df2['나이']*df2['점수']/100
df2

        이름  나이   점수   보너스
학생1   Jane  34   80  27.2
학생2    Tom  27   70  18.9
학생3  Alice  51   90  45.9
학생4   Hong  45  100  45.0

In [78]:
import numpy as np
df2['비고'] = np.nan
df2

        이름  나이   점수   보너스  비고
학생1   Jane  34   80  27.2 NaN
학생2    Tom  27   70  18.9 NaN
학생3  Alice  51   90  45.9 NaN
학생4   Hong  45  100  45.0 NaN

In [83]:
df2.loc['학생2',:]
df2.loc['학생2':'학생2',:] #indexing을 이용하여 행으로 표현
df2[df2['이름']=='Tom'] #Tom인 사람만 추출
df2[df2.이름.str.find('Tom')>-1] #True만 추출 / 오래된 방식
df2[df2.이름.str.contains('Tom', na = False)] #빈 값 제외, 최근 방식

      이름  나이  점수   보너스  비고
학생2  Tom  27  70  18.9 NaN

In [89]:
d3 = {'name': ['Jane','Tom','Alice','Jogn'],
      'age' : [34,27,51,45],
      'point' : [80,70,90,60]}

df3 = pd.DataFrame(d3,columns=['name','point','age','etc'],
                   index = ['학생1', '학생2','학생3', '학생4'])
df3

print(df3['point'].sum())
print(df3['point'].mean())

300
75.0

### CSV 자료관리 Sol3

1. Google Drive 경로상에서 찾기
2. Gitgub사이트에서 찾아 url 첨부
3. 파일로 저장하여 끌어오기
4. Excel 읽어오기 - openpyxl 라이브러리 사용

In [1]:
#Sol1

filename = '/content/drive/MyDrive/quest.csv'
f1 = open(filename, 'r')
d1 = f1.read()
f1.close()
print(d1)

1,2,1,2,2
1,3,2,3,2
1,4,3,3,3
2,5,4,4,4
2,5,6,2,5
3,6,4,2,5
3,5,4,1,6
3,5,5,1,3

In [3]:
import csv
f2 = open(filename,'r')
new = csv.reader(f2)
d2 = []
for d in new:
  d2.append(d)
f2.close()

print(d2)

[['1', '2', '1', '2', '2'], ['1', '3', '2', '3', '2'], ['1', '4', '3', '3', '3'], ['2', '5', '4', '4', '4'], ['2', '5', '6', '2', '5'], ['3', '6', '4', '2', '5'], ['3', '5', '4', '1', '6'], ['3', '5', '5', '1', '3']]

In [4]:
#Sol2

filename='https://raw.githubusercontent.com/devdio/datasets/main/iris.csv'
import pandas as pd
df = pd.read_csv(filename)
df.head()

# f1 = open(filename,'r')
# d1 = f1.read()
# f1.close()
# open 으로는 읽을 수 없음!

   Sepal Length  Sepal Width  Petal Length  Petal Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

- titanic data
- https://www.kaggle.com/competitions/titanic/data
- https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv

In [5]:
filename='https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'
import pandas as pd
df = pd.read_csv(filename)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
!gdown https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv

Downloading...
From: https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv
To: /content/titanic.csv
60.1kB [00:00, 43.5MB/s]

In [8]:
#Sol3

import pandas as pd

titanic = pd.read_csv('titanic.csv')
titanic.head()

print('type : ', type(titanic))
print('shape : ', titanic.shape)

type :  <class 'pandas.core.frame.DataFrame'>
shape :  (891, 12)

- 함수
  - head()
  - tail()
  - info()
  - describe()

In [15]:
titanic.tail(3)
titanic.head(4)
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [16]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
titanic.columns.to_list()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

### 결측치 (Missing Value) 처리

- DataFrame생성, 결측치 뽑기

In [22]:
import numpy as np
import pandas as pd

z = [['Jackson', 68, True, np.nan, 'A'],
     ['Liam', 74, True, 1.1, 'A'],
     ['Emma', np.nan, False, 0.89, 'C'],
     ['James', 78, np.nan, 0.91, 'C'],
     ['Ava', 54, False, 0.73, 'C'],
     ['Henry', 69, True, np.nan, 'C']]

df = pd.DataFrame(data = z, columns=['Name', 'Weight', 'Option', 'Rate', 'Type'])

df

      Name  Weight Option  Rate Type
0  Jackson    68.0   True   NaN    A
1     Liam    74.0   True  1.10    A
2     Emma     NaN  False  0.89    C
3    James    78.0    NaN  0.91    C
4      Ava    54.0  False  0.73    C
5    Henry    69.0   True   NaN    C

In [24]:
df.isna().sum()

Name      0
Weight    1
Option    1
Rate      2
Type      0
dtype: int64

- 결측치 처리
  - dropna()
  - fillna()

In [33]:
df.dropna()
df.fillna(0)

      Name  Weight Option  Rate Type
0  Jackson    68.0   True  0.00    A
1     Liam    74.0   True  1.10    A
2     Emma     0.0  False  0.89    C
3    James    78.0      0  0.91    C
4      Ava    54.0  False  0.73    C
5    Henry    69.0   True  0.00    C

In [39]:
m = df['Weight'].mean()
print('mean : ', m)

df['Weight'].fillna(m, inplace=True)
df

mean :  64.0

/tmp/ipykernel_2566/3287577748.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Weight'].fillna(m, inplace=True)

   Name  Weight Option  Rate Type
1  Liam    74.0   True  1.10    A
4   Ava    54.0  False  0.73    C

In [36]:
z = [['Jackson', 68, True, np.nan, 'A'],
     ['Liam', 74, True, 1.1, 'A'],
     ['Emma', np.nan, False, 0.89, 'C'],
     ['James', 78, np.nan, 0.91, 'C'],
     ['Ava', 54, False, 0.73, 'C'],
     ['Henry', 69, True, np.nan, 'C']]

df = pd.DataFrame(data=z, columns = ['Name','Weight','Option','Rate','Type'])

re = df.dropna()
df

      Name  Weight Option  Rate Type
0  Jackson    68.0   True   NaN    A
1     Liam    74.0   True  1.10    A
2     Emma     NaN  False  0.89    C
3    James    78.0    NaN  0.91    C
4      Ava    54.0  False  0.73    C
5    Henry    69.0   True   NaN    C

In [37]:
re = df.dropna(inplace=True)
df

   Name  Weight Option  Rate Type
1  Liam    74.0   True  1.10    A
4   Ava    54.0  False  0.73    C

### 인덱싱과 슬라이싱 복습

In [2]:
import pandas as pd
import numpy as np

x = [['Jackson', 68, True, np.nan, 'A'],
     ['Liam', 74, True, 1.1, 'A'],
     ['Emma', np.nan, False, 0.89, 'C'],
     ['James', 78, np.nan, 0.91, 'C'],
     ['Ava', 54, False, 0.73, 'C'],
     ['Henry', 69, True, np.nan, 'C']]

df = pd.DataFrame(x, columns=['Name', 'Weight', 'Option', 'Rate', 'Type'])
df

      Name  Weight Option  Rate Type
0  Jackson    68.0   True   NaN    A
1     Liam    74.0   True  1.10    A
2     Emma     NaN  False  0.89    C
3    James    78.0    NaN  0.91    C
4      Ava    54.0  False  0.73    C
5    Henry    69.0   True   NaN    C

In [3]:
tx = df.loc[2:4, ['Name', 'Weight']]
tx

    Name  Weight
2   Emma     NaN
3  James    78.0
4    Ava    54.0

In [4]:
x2 = df.loc[df['Rate']>0.8, ['Weight', 'Rate', 'Type']]
x2

   Weight  Rate Type
1    74.0  1.10    A
2     NaN  0.89    C
3    78.0  0.91    C

In [8]:
x3 = df.loc[(df['Rate']>0.8) & (df['Option']==True)]
x3

   Name  Weight Option  Rate Type
1  Liam    74.0   True   1.1    A

In [11]:
x4 = df.select_dtypes(include=['number'])
x4
df['Type']='A'
df

      Name  Weight Option  Rate Type
0  Jackson    68.0   True   NaN    A
1     Liam    74.0   True  1.10    A
2     Emma     NaN  False  0.89    A
3    James    78.0    NaN  0.91    A
4      Ava    54.0  False  0.73    A
5    Henry    69.0   True   NaN    A

In [15]:
df.rename(columns={'Type':'Grade'}, inplace=True)
df.columns = ['A','B', 'C', 'D','E']
df

         A     B      C     D  E
0  Jackson  68.0   True   NaN  A
1     Liam  74.0   True  1.10  A
2     Emma   NaN  False  0.89  A
3    James  78.0    NaN  0.91  A
4      Ava  54.0  False  0.73  A
5    Henry  69.0   True   NaN  A

In [21]:
x = [['Jackson', 68, True, 0.82, 'A'],
['Liam', 74, True, 1.1, 'B'],
['Emma', 52, False, 0.89, 'C'],
['James', 78, True, 0.91, 'C'],
['Ava', 54, False, 0.73, 'B'],
['Henry', 69, True, 0.78, 'C']]
df = pd.DataFrame(x, columns=['Name', 'Weight', 'Option',
'Rate', 'Type'])

df.loc[df['Option']==False, 'Type'] = np.nan
df.drop(['Option', 'Weight'], axis=1, inplace=True)
df

      Name  Rate Type
0  Jackson  0.82    A
1     Liam  1.10    B
2     Emma  0.89  NaN
3    James  0.91    C
4      Ava  0.73  NaN
5    Henry  0.78    C

In [23]:
df = pd.DataFrame({
'Weight':['68', '74','52','78','54','69'],
'Option':[True, True, False, True, False, True],
'Rate':[0.82, 1.1, 0.89, 0.91, 0.73, 0.78],
'Type':['A','B','C','C','B','C']
})
df['Weight'] = pd.to_numeric(df['Weight'])
df['Weight'] = df['Weight'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  6 non-null      object
 1   Option  6 non-null      bool
 2   Rate    6 non-null      float64
 3   Type    6 non-null      object
dtypes: bool(1), float64(1), object(2)
memory usage: 282.0+ bytes

### 통계 데이터 계산

In [26]:
import pandas as pd
!gdown https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv
titanic = pd.read_csv('titanic.csv')

titanic.count()

Downloading...
From: https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv
To: /content/titanic.csv
60.1kB [00:00, 58.9MB/s]

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [29]:
x = titanic['Sex'].value_counts()
print(x)

y = titanic['Embarked'].unique()
print(y)

z = titanic.mean(numeric_only=True)
print(z)

Sex
male      577
female    314
Name: count, dtype: int64
['S' 'C' 'Q' nan]
PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [31]:
x = titanic.loc[titanic['Sex']=='female', 'Age']
x.mean()

np.float64(27.915708812260537)

### 그룹핑
- groupby() : 특정 칼럼의 값을 기준으로 그룹핑해서 함수를 실행한다.
- map : 단일컬럼에서 apply()랑 같은 기능

In [32]:
df = pd.DataFrame({
'city': ['Busan', 'Busan', 'Busan', 'Busan',
'Seoul', 'Seoul', 'Seoul'],
'fruits': ['Apple', 'Orange', 'Banana',
'Banana', 'Apple', 'Apple', 'Banana'],
'price': [100, 200, 250, 300, 150, 200, 400],
'quantity': [1, 2, 3, 4, 5, 6, 7]
})
df

    city  fruits  price  quantity
0  Busan   Apple    100         1
1  Busan  Orange    200         2
2  Busan  Banana    250         3
3  Busan  Banana    300         4
4  Seoul   Apple    150         5
5  Seoul   Apple    200         6
6  Seoul  Banana    400         7

In [33]:
x = df.groupby('city')['price'].mean()
x

city
Busan    212.5
Seoul    250.0
Name: price, dtype: float64

In [34]:
x = df.groupby(['city','fruits']).mean()
x

              price  quantity
city  fruits
Busan Apple   100.0       1.0
      Banana  275.0       3.5
      Orange  200.0       2.0
Seoul Apple   175.0       5.5
      Banana  400.0       7.0

In [35]:
df = pd.DataFrame([[4,9]]*3, columns=['A','B'])
df

   A  B
0  4  9
1  4  9
2  4  9

In [37]:
x = df.apply(np.sqrt) #변수처럼 보이지만 함수임
x
#apply(함수)

     A    B
0  2.0  3.0
1  2.0  3.0
2  2.0  3.0

In [39]:
x = df.apply(np.sum, axis = 1) #축 (0->행, 1->열)
x

0    13
1    13
2    13
dtype: int64

### map()

In [40]:
df = pd.DataFrame({
'city': ['Busan', 'Busan', 'Busan', 'Busan',
'Seoul', 'Seoul', 'Seoul'],
'fruits': ['Apple', 'Orange', 'Banana',
'Banana', 'Apple', 'Apple', 'Banana'],
'price': [100, 200, 250, 300, 150, 200, 400],
'quantity': [1, 2, 3, 4, 5, 6, 7]
})
df

    city  fruits  price  quantity
0  Busan   Apple    100         1
1  Busan  Orange    200         2
2  Busan  Banana    250         3
3  Busan  Banana    300         4
4  Seoul   Apple    150         5
5  Seoul   Apple    200         6
6  Seoul  Banana    400         7

In [42]:
z = df['city'].map(lambda x:'SEO' if x=='Seoul' else 'BUS')
df['TAG'] = z
df

    city  fruits  price  quantity  TAG
0  Busan   Apple    100         1  BUS
1  Busan  Orange    200         2  BUS
2  Busan  Banana    250         3  BUS
3  Busan  Banana    300         4  BUS
4  Seoul   Apple    150         5  SEO
5  Seoul   Apple    200         6  SEO
6  Seoul  Banana    400         7  SEO

In [43]:
df['TAG'] = df['TAG'].map({'BUS':0, 'SEO':1})
df

    city  fruits  price  quantity  TAG
0  Busan   Apple    100         1    0
1  Busan  Orange    200         2    0
2  Busan  Banana    250         3    0
3  Busan  Banana    300         4    0
4  Seoul   Apple    150         5    1
5  Seoul   Apple    200         6    1
6  Seoul  Banana    400         7    1